vaadin.launch-browser=true
spring.application.name=Graft
spring.neo4j.uri=neo4j+s://b85a5708.databases.neo4j.io
spring.neo4j.authentication.username=b85a5708
spring.neo4j.authentication.password=C9V6UPmelS68eiB-KtrOQ4TydbDhoJoA_ZhrWdm0WW4